name: Windows RDP via ZeroTier

on:
  workflow_dispatch:
    inputs:
      zerotier_network:
        description: "ID da sua rede ZeroTier"
        required: true
      zerotier_token:
        description: "Token de API do ZeroTier (se precisar autorizar auto)"
        required: false

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixar instalador do ZeroTier
        run: |
          $url = "https://download.zerotier.com/dist/ZeroTierOne.msi"
          $dst = "$env:TEMP\ZeroTierOne.msi"
          Invoke-WebRequest -Uri $url -OutFile $dst
          Start-Process msiexec.exe -ArgumentList "/i `"$dst`" /quiet /norestart" -Wait

      - name: Conectar ao ZeroTier
        run: |
          Start-Process -FilePath "C:\Program Files\ZeroTier\One\zerotier-cli.bat" -ArgumentList "join ${{ github.event.inputs.zerotier_network }}" -Wait
          Start-Sleep -Seconds 10
          & "C:\Program Files\ZeroTier\One\zerotier-cli.bat" listnetworks

      # (Opcional) autorizar o nó automaticamente pela API
      - name: Autorizar nó via API
        if: ${{ github.event.inputs.zerotier_token != '' }}
        run: |
          $nodeId = (& "C:\Program Files\ZeroTier\One\zerotier-cli.bat" info).Split(" ")[2]
          $authUrl = "https://api.zerotier.com/api/v1/network/${{ github.event.inputs.zerotier_network }}/member/$nodeId"
          $headers = @{ "Authorization" = "Bearer ${{ github.event.inputs.zerotier_token }}" }
          $body = '{ "authorized": true }'
          Invoke-RestMethod -Uri $authUrl -Headers $headers -Method POST -Body $body -ContentType "application/json"

