name: Windows RDP via ZeroTier

on:
  workflow_dispatch:
    inputs:
      zerotier_network:
        description: "ID da rede ZeroTier (ex: 8056c2e21c000001)"
        required: true
      zerotier_token:
        description: "API Token do ZeroTier (opcional, para autorizar auto)"
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Instalar ZeroTier
        run: |
          $url = "https://download.zerotier.com/dist/ZeroTierOne.msi"
          $dst = "$env:TEMP\ZeroTierOne.msi"
          Invoke-WebRequest -Uri $url -OutFile $dst
          Start-Process msiexec.exe -ArgumentList "/i `"$dst`" /quiet /norestart" -Wait

      - name: Entrar na rede ZeroTier
        run: |
          Start-Process -FilePath "C:\Program Files\ZeroTier\One\zerotier-cli.bat" -ArgumentList "join ${{ github.event.inputs.zerotier_network }}" -Wait
          Start-Sleep -Seconds 10
          & "C:\Program Files\ZeroTier\One\zerotier-cli.bat" listnetworks

      - name: Autorizar nó automaticamente (opcional)
        if: ${{ github.event.inputs.zerotier_token != '' }}
        run: |
          $nodeId = (& "C:\Program Files\ZeroTier\One\zerotier-cli.bat" info).Split(" ")[2]
          $authUrl = "https://api.zerotier.com/api/v1/network/${{ github.event.inputs.zerotier_network }}/member/$nodeId"
          $headers = @{ "Authorization" = "Bearer ${{ github.event.inputs.zerotier_token }}" }
          $body = '{ "authorized": true }'
          Invoke-RestMethod -Uri $authUrl -Headers $headers -Method POST -Body $body -ContentType "application/json"

      - name: Habilitar RDP
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Write-Host "RDP habilitado com sucesso!"
